### ISSUE TITLE
How to save money for investment - personal finances.

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/handbook-of-money#4]
Tips and tricks for saving money. List of resources for personal finances.

**Comment by ineagu** [comment]
I initially skipped this because I pretty much never think about saving in a way that most of the people would do, however I do have some principles.

I don't get in debt and  I like to leave below my means, I always found it easier to think on how I can increase my earnings,  in order to save more, rather than reduce my spending.

I also like to in a way artificially lower my monthly income to avoid spending too much, like I worked a couple of years basically for equity vs salary.

I think that while you are young there are simply lots of opportunities on the investment side, investing in yourself mostly so you can generate more income, rather than spending time thinking on how you can save.

**Comment by ineagu** [comment]
I also remember that I had the mindset that I can pretty much live close to 0 expenses. Once I envied a friend who eat the same food for 1 week, cooked once for cheap. I did that as well, I thought that I can save both time & money. Didn't think too much about health :D 

For the first part of my working life & company life, I lived very cheaply and invested everything back. With all the freelancing money I tried to build passive income.

**Comment by mileamadalin** [comment]
Some ideas from what I do. 

Although saving 20% of the monthly income is recommended, sometimes I succeed, and sometimes I save only 10% (any amount is better than nothing) for various reasons and unexpected expenses that arise (someone hits your car and flees the scene of the accident - you have to repair it yourself; or some checks related to health, etc.).

Thinking that inflation will erode my money, every month, from the amount I decide to save, half I put in the savings account. For the other half, I try to invest in stocks (if the amount is not enough to cover what I want to purchase, I deposit the money anyway and buy when I have collected the amount I need).
Another good practice is to have a reserve account were to add 2-3 salaries for emergencies.
