### ISSUE TITLE
Introduction to investment.

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/handbook-of-money#5]
Resources for beginners in investment. How to avoid scams, etc. Personal opinions or strategies.

**Comment by ineagu** [comment]
A rule that I always knew and it helped me is that there is no free lunch. There is no way that you do nothing that your money just grows by investing in whatever people are promoting nowadays.

Every investment has a risk, the higher the return, the higher the risk.

If you want to have an "edge", which means to earn more, with a lower risk you need to bring something to the table.

For e.g I am hoping for more return by investing in a wordpress plugin, because we do have the know-how and we'll put the work to get better than average results.

**Comment by ineagu** [comment]
There is pretty much no way as a random person you know when the USD would go up or down, when the market would go up or down, I think you need to be humble and realise that without knowing more that most of the people, you can't have better results that most of the people.
