### ISSUE TITLE
Channel to follow for investment, books to read.

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/handbook-of-money#6]
Resources that keep up to date with the investment world.

**Comment by mileamadalin** [comment]
Books recommendation:

- [The intelligent investor](https://www.amazon.com/Intelligent-Investor-Definitive-Investing-Essentials/dp/0060555661/ref=sr_1_4?crid=2GE3X6RT8XZUO&keywords=the+inteligent+investor&qid=1652953715&sprefix=the+intelligent+investor%2Caps%2C190&sr=8-4) by _Benjamin Graham_
- [The Snowball: Warren Buffett and the Business of Life](https://www.amazon.com/Snowball-Buffett-Business-Simplified-Chinese/dp/B001W4DH8U/ref=sr_1_3?crid=1C7Q3R09QBC5O&keywords=The+Snowball%3A+Warren+Buffett+and+the+Business+of+Life&qid=1652953923&sprefix=the+snowball+warren+buffett+and+the+business+of+life+%2Caps%2C366&sr=8-3) by _Alice Schroeder_

Podcasts recommendation:

Berkshire Hathaway Annual Shareholder Meetings https://podcasts.apple.com/ro/podcast/berkshire-hathaway-annual-shareholder-meetings-since/id1445276006  -> here is also a [video](https://www.cnbc.com/video/2022/05/01/watch-warren-buffett-and-charlie-munger-preside-over-full-berkshire-hathaway-annual-meeting.html) from the last one

**Comment by ineagu** [comment]
I would say here, just read whatever you find that would help you understand the WHOLE picture. You need to understand politics, finance, how markets tend to work, stock vs credit market, and how big funds operate, taxes.

For e.g you can have a US company that withholds 35% of tax on dividends, while if you own shares in a romanian company, you pay 5%.

**Comment by ineagu** [comment]
so you have all the context to dig deep into the company reporting. For e.g lots of new companies have 40% of the stock that plans to issue to employees, this would basically dilute your holdings by 40%. If there are stock options, how much and at what strike price.
