### ISSUE TITLE
How to read Financial Graphs And Charts and evaluate a company.

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/handbook-of-money#7]
A small tutorial on how to read financial graphs and charts. How to use them to check if a company is worth investing in it.

**Comment by mileamadalin** [comment]
Since Warren Buffet is a long-term investor, I think his way of looking at the company’s profitability suits well to our Handbook Of Money. Here is a short brief with five points we can consider while researching where to put the money. 

INTERPRETATION OF FINANCIAL STATEMENTS

“The best holding period for an investment is forever”  — Warren Buffet. 

1. Consistency is King 
- consistency in earning 
- consistent law debt
- consistently growing earning
- consistently low spending in expenditures and R&D
- consistent profitability

If we took the Coca-Cola company, created in 1900, the longer the company has been proving its durability, the better. 

Why this? Because they are selling almost the same product, that’s a great advantage for the stock owners because it reduces costs (by a lot in the long run). 

Costs are cut in many areas: production costs, marketing costs, research, and development, lower training costs of employees, etc.

2. Income Statement

At want to look at an income statement

- Net income (loss)
- Gross Profit (consistent gross margin; here, you want to see a margin of +40%)
- A net margin of 20% or higher is a solid result

3. Balance Sheet

- Retained Earnings (here, you can see if the company is reinvesting its net income or not; if a company shows growth here, that could mean the business is profitable and identifies good reinvesting opportunities).
- Return of Equity can measure how efficiently a company is using these reinvested earnings. To calculate this one, we need to compare the Net income with the Total Equity (Net Income / Total Equity = ROE)
- Look for a business with little to no long-term debt (if the company can pay all of its long-term debt with less than four years of earning, it’s in a good position). 

4. Cashflow Statement 

- Capital expenditures (money spent on properties, plants, and equipment). At that point, you need to look at % the capital expenditures of net earnings; you want them to be as low as possible (lower than 25% is considered very good, and less than 50% is acceptable - however, an exception can be when a company is making a one-time payment to grow the business). 

% calculation:  capital expenditures / net income(%)

5. When to Sell

Even if we started with the quote, “The best holding period for an investment is forever,”; there are three instances when you might consider selling your stocks. 

- You need more money for an even better investment
- When a company may lose its competitive advantage
- During crazy bull markets

Mary Buffett and David Clark suggest that you should start to consider selling your stocks at a PE ratio of 40 or higher.

———————————————————————

Below I posted a [YouTube](https://www.youtube.com/watch?v=lBBXmim527A 
) video where someone explained how Warren Buffett interprets the financial statements. Also, even more, details are found in the [book](https://www.amazon.com/gp/product/1849833192/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1849833192&linkCode=as2&tag=1234502d98-20&linkId=1b3a260435b680a8543bf4eebb673cf0) “Warren Buffett and the Interpretation of Financial Statements.”

https://www.youtube.com/watch?v=lBBXmim527A 

https://www.amazon.com/gp/product/1849833192/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1849833192&linkCode=as2&tag=1234502d98-20&linkId=1b3a260435b680a8543bf4eebb673cf0

**Comment by mileamadalin** [comment]
How to read charts

How to read a chart

The stock chart is a graph that displays the price of an investment over a period of time. You can use the charts to forecast future price movements. 

The primary purpose of any chart is to show you: 
- the price of an investment
- change over time

The most used are: 

- Line chart 

<img width="878" alt="Screen Shot 2022-05-19 at 12 40 24" src="https://user-images.githubusercontent.com/6906834/169263673-370b17ac-e1d0-4564-88ef-badd325e631f.png">

- Bar Chart

<img width="887" alt="Screen Shot 2022-05-19 at 12 41 48" src="https://user-images.githubusercontent.com/6906834/169263958-a669d532-bdf9-4c3a-a79d-f498d27163fd.png">

- Candlestick Chart

<img width="888" alt="Screen Shot 2022-05-19 at 12 42 57" src="https://user-images.githubusercontent.com/6906834/169264160-617aaa2e-4817-451c-b065-38b54f44cb1c.png">

_Personally, I use the line chart more when I look at companies because I look at the last 1-3 years and how it has evolved from listing to the present. This makes it easier for me to make an impression. --- Madalin _ 

[Here](https://www.youtube.com/watch?v=Lz9ysR-a0RQ) is a short video with all the details https://www.youtube.com/watch?v=Lz9ysR-a0RQ

**Comment by ineagu** [comment]
> Since Warren Buffet is a long-term investor, I think his way of looking at the company’s profitability suits well to our Handbook Of Money. Here is a short brief with five points we can consider while researching where to put the money.
> 
> INTERPRETATION OF FINANCIAL STATEMENTS
> 
> “The best holding period for an investment is forever” — Warren Buffet.
> 
> 1. Consistency is King
> 
> * consistency in earning
> * consistent law debt
> * consistently growing earning
> * consistently low spending in expenditures and R&D
> * consistent profitability
> 
> If we took the Coca-Cola company, created in 1900, the longer the company has been proving its durability, the better.
> 
> Why this? Because they are selling almost the same product, that’s a great advantage for the stock owners because it reduces costs (by a lot in the long run).
> 
> Costs are cut in many areas: production costs, marketing costs, research, and development, lower training costs of employees, etc.
> 
> 2. Income Statement
> 
> At want to look at an income statement
> 
> * Net income (loss)
> * Gross Profit (consistent gross margin; here, you want to see a margin of +40%)
> * A net margin of 20% or higher is a solid result
> 
> 3. Balance Sheet
> 
> * Retained Earnings (here, you can see if the company is reinvesting its net income or not; if a company shows growth here, that could mean the business is profitable and identifies good reinvesting opportunities).
> * Return of Equity can measure how efficiently a company is using these reinvested earnings. To calculate this one, we need to compare the Net income with the Total Equity (Net Income / Total Equity = ROE)
> * Look for a business with little to no long-term debt (if the company can pay all of its long-term debt with less than four years of earning, it’s in a good position).
> 
> 4. Cashflow Statement
> 
> * Capital expenditures (money spent on properties, plants, and equipment). At that point, you need to look at % the capital expenditures of net earnings; you want them to be as low as possible (lower than 25% is considered very good, and less than 50% is acceptable - however, an exception can be when a company is making a one-time payment to grow the business).
> 
> % calculation: capital expenditures / net income(%)
> 
> 5. When to Sell
> 
> Even if we started with the quote, “The best holding period for an investment is forever,”; there are three instances when you might consider selling your stocks.
> 
> * You need more money for an even better investment
> * When a company may lose its competitive advantage
> * During crazy bull markets
> 
> Mary Buffett and David Clark suggest that you should start to consider selling your stocks at a PE ratio of 40 or higher.
> 
> ———————————————————————
> 
> Below I posted a [YouTube](https://www.youtube.com/watch?v=lBBXmim527A) video where someone explained how Warren Buffett interprets the financial statements. Also, even more, details are found in the [book](https://www.amazon.com/gp/product/1849833192/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1849833192&linkCode=as2&tag=1234502d98-20&linkId=1b3a260435b680a8543bf4eebb673cf0) “Warren Buffett and the Interpretation of Financial Statements.”
> 
> https://www.youtube.com/watch?v=lBBXmim527A
> 
> https://www.amazon.com/gp/product/1849833192/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1849833192&linkCode=as2&tag=1234502d98-20&linkId=1b3a260435b680a8543bf4eebb673cf0
> 
> Later edit: Bonus video "Warren Buffett: How To Invest For Beginners " https://www.youtube.com/watch?v=yRr0_gJ-3mI

I've read that Mary Buffett stuff and is kind of crappy, there are a lot of better stuff. Also the advice to sell when P/E = 40 is very bad. If a company is taking some sort of temporary hit, the PE would go up a lot, it doesn't really mean is a problem. Just don't do that.

I think you need to sell once you're initial assumptions change. If you mainly bought a stock because you think the ceo is great and would make a difference, you would sell when he leaves. If you bought it because is has big dividend, you would sell when dividend is low. If you bought because it's a high quality business, you would sell when it decrease in quality.

**Comment by mileamadalin** [comment]
Thank you for sharing your thoughts with us. You're right with your points. At the same time, I'm sure there are some exceptions for different scenarios with a one-time thing.

> If you mainly bought a stock because you think the ceo is great and would make a difference, you would sell when he leaves.

That's a good one; I saw in one of Warren Buffet's videos that he said something similar also; he was looking to see the management team and is the trust the group will invest if not, not, or sell it if already have that stock. 

We can remove that suggestion 

> Mary Buffett and David Clark suggest that you should start to consider selling your stocks at a PE ratio of 40 or higher.

if it's a bad one. But the other details do you find helpful? If not, could you please help us here with some advice we can use for evaluating a company?

**Comment by ineagu** [comment]
Regarding your last point, again, I think you need to sell/re-consider once your initial assumptions are not true anymore. Sure you can also sell when close to overvalued.

In order to see if a company is overvalued, you need to look both at P/E, debt, and growth. If the company is growing fast, PE = 40, is cheap. If the company is not growing, is likely over-valued.

Some companies like Berkshire who owns securities, need to report the unrealized gains in securities as earnings, which doesn't make any sense. So based on stock market, they can have 3-4 PE or 400 PE
